#Basic Tricks
tricklist = [
["Backside 180","Regular / Goofy"],
["Backside 360","Regular / Goofy"],
["Backside Caballerial","Fakie"],
["Backside Half Cab","Regular / Goofy"],
["Fakie Ollie","Fakie"],
["Frontside 180","Regular / Goofy"],
["Frontside 360","Regular / Goofy"],
["Frontside Caballerial","Fakie"],
["Frontside Half Cab","Fakie"],
["Nollie","Nollie"],
["Nollie Backside 180","Nollie"],
["Nollie Backside 360","Nollie"],
["Nollie Frontside 180","Nollie"],
["Nollie Frontside 360","Nollie"],
["Ollie","Regular / Goofy"],
["Powerslide","Regular / Goofy"],
["Switch Backside 180","Switch"],
["Switch Backside 360","Switch"],
["Switch Frontside 180","Switch"],
["Switch Frontside 360","Switch"],
["Switch Ollie","Switch"],
["360 Flip","Regular / Goofy"],
["360 Hardflip","Regular / Goofy"],
["360 Ollie Heelflip","Regular / Goofy"],
["360 Ollie Kickflip","Regular / Goofy"],
["360 Pop Shove-it","Regular / Goofy"],
["360 Shuvit","Regular / Goofy"],
["540 Flip","Regular / Goofy"],
["720 Flip","Regular / Goofy"],
["Backside Bigspin","Regular / Goofy"],
["Backside Half Cab Heelflip","Fakie"],
["Backside Half Cab Kickflip","Fakie"],
["Backside Heelflip","Regular / Goofy"],
["Backside Kickflip","Regular / Goofy"],
["Big Heelflip","Regular / Goofy"],
["Bigflip","Regular / Goofy"],
["Biggerflip","Regular / Goofy"],
["Biggerspin","Regular / Goofy"],
["Bigspin","Regular / Goofy"],
["Caballerial Flip","Fakie"],
["Double Heelflip","Regular / Goofy"],
["Double Kickflip","Regular / Goofy"],
["Fakie 360 Flip","Fakie"],
["Fakie 360 Hardflip","Fakie"],
["Fakie Backside Bigspin","Fakie"],
["Fakie Backside Pop Shove-it","Fakie"],
["Fakie Frontside Bigspin","Fakie"],
["Fakie Frontside Pop Shove-it","Fakie"],
["Fakie Hardflip","Fakie"],
["Fakie Heelflip","Fakie"],
["Fakie Inward Heelflip","Fakie"],
["Fakie Kickflip","Fakie"],
["Fakie Varial Heelflip","Fakie"],
["Fakie Varial Kickflip","Fakie"],
["Forward Flip","Regular / Goofy"],
["Frontside 360 Pop Shove it","Regular / Goofy"],
["Frontside Bigspin","Regular / Goofy"],
["Frontside Half Cab Heelflip","Fakie"],
["Frontside Half Cab Kickflip","Fakie"],
["Frontside Heelflip","Regular / Goofy"],
["Frontside Kickflip","Regular / Goofy"],
["Frontside Pop Shove-it","Regular / Goofy"],
["Gazelle Flip","Regular / Goofy"],
["Gazelle Spin","Regular / Goofy"],
["Ghetto Bird","Regular / Goofy"],
["Half Cab","Fakie"],
["Hardflip","Regular / Goofy"],
["Heelflip","Regular / Goofy"],
["Inward Heelflip","Regular / Goofy"],
["Kickflip","Regular / Goofy"],
["Laser Flip","Regular / Goofy"],
["Nollie 360 Flip","Nollie"],
["Nollie 360 Hardflip","Nollie"],
["Nollie 360 Pop Shove-it","Nollie"],
["Nollie Backside Bigspin","Nollie"],
["Nollie Backside Heelflip","Nollie"],
["Nollie Backside Kickflip","Nollie"],
["Nollie Backside Pop Shove-it","Nollie"],
["Nollie Frontside Bigspin","Nollie"],
["Nollie Frontside Heelflip","Nollie"],
["Nollie Frontside Kickflip","Nollie"],
["Nollie Frontside Pop Shove-it","Nollie"],
["Nollie Hardflip","Nollie"],
["Nollie Heelflip","Nollie"],
["Nollie Inward Heelflip","Nollie"],
["Nollie Kickflip","Nollie"],
["Nollie Laser Flip","Nollie"],
["Nollie Varial Heelflip","Nollie"],
["Nollie Varial Kickflip","Nollie"],
["Shuvit","Regular / Goofy"],
["Switch 360 Flip","Switch"],
["Switch 360 Hardflip","Switch"],
["Switch Backside Bigspin","Switch"],
["Switch Backside Heelflip","Switch"],
["Switch Backside Kickflip","Switch"],
["Switch Backside Pop Shove-it","Switch"],
["Switch Frontside Bigspin","Switch"],
["Switch Frontside Heelflip","Switch"],
["Switch Frontside Kickflip","Switch"],
["Switch Frontside Pop Shove-it","Switch"],
["Switch Hardflip","Switch"],
["Switch Heelflip","Switch"],
["Switch Inward Heelflip","Switch"],
["Switch Kickflip","Switch"],
["Switch Laser Flip","Switch"],
["Switch Varial Heelflip","Switch"],
["Switch Varial Kickflip","Switch"],
["Triple Kickflip","Regular / Goofy"],
["Varial Heelflip","Regular / Goofy"],
["Varial Kickflip","Regular / Goofy"]]