#Grind and Slide Tricks,
tricklist = [
["50-50 Grind",],
["Backside 5-0","Regular / Goofy"],
["Backside 50-50","Regular / Goofy"],
["Backside Bluntslide","Regular / Goofy"],
["Backside Boardslide","Regular / Goofy"],
["Backside Crooked","Regular / Goofy"],
["Backside Feeble","Regular / Goofy"],
["Backside Lipslide","Regular / Goofy"],
["Backside Noseblunt Slide","Regular / Goofy"],
["Backside Nosegrind","Regular / Goofy"],
["Backside Noseslide","Regular / Goofy"],
["Backside Overcrook","Regular / Goofy"],
["Backside Salad","Regular / Goofy"],
["Backside Smith","Regular / Goofy"],
["Backside Suski","Regular / Goofy"],
["Backside Tailslide","Regular / Goofy"],
["Barley Grind","Regular / Goofy"],
["Bertlemann Slide","Regular / Goofy"],
["Bluntslide","Regular / Goofy"],
["Boardslide","Regular / Goofy"],
["Casper Slide","Regular / Goofy"],
["Crail Slide","Regular / Goofy"],
["Crooked Grind","Regular / Goofy"],
["Darkslide","Regular / Goofy"],
["Feeble Grind","Regular / Goofy"],
["Frontside 5-0","Regular / Goofy"],
["Frontside 50-50","Regular / Goofy"],
["Frontside Bluntslide","Regular / Goofy"],
["Frontside Boardslide","Regular / Goofy"],
["Frontside Crooked","Regular / Goofy"],
["Frontside Feeble","Regular / Goofy"],
["Frontside Lipslide","Regular / Goofy"],
["Frontside Noseblunt Slide","Regular / Goofy"],
["Frontside Nosegrind","Regular / Goofy"],
["Frontside Noseslide","Regular / Goofy"],
["Frontside Overcrook","Regular / Goofy"],
["Frontside Salad","Regular / Goofy"],
["Frontside Smith","Regular / Goofy"],
["Frontside Suski","Regular / Goofy"],
["Frontside Tailslide","Regular / Goofy"],
["Hurricane","Regular / Goofy"],
["Hurricane Grind","Regular / Goofy"],
["Layback Grind","Regular / Goofy"],
["Lipslide","Regular / Goofy"],
["Nail Slide","Regular / Goofy"],
["Noseblunt Slide","Regular / Goofy"],
["Nosegrind","Regular / Goofy"],
["Noseslide","Regular / Goofy"],
["Overcrook Grind","Regular / Goofy"],
["Overturn","Regular / Goofy"],
["Primo Grind","Regular / Goofy"],
["Salad Grind","Regular / Goofy"],
["Slash Grind","Regular / Goofy"],
["Smith Grind","Regular / Goofy"],
["Suski Grind","Regular / Goofy"],
["Tailblock Grind","Regular / Goofy"],
["Tailslide","Regular / Goofy"],
["Willy Grinds","Regular / Goofy"]]
